### ISSUE TITLE
[suggestion] Add proper translation support

### ISSUE THREAD

**Issue by rene-coty** [Sjoerd1993/Graphs#232]
I would like to contribute to the app by providing a French translation, but as I am not very familiar with coding, I need to get a .pot file containing the translatable strings or at least a method to build it (this is a thing I am technically not able to do myself).. would it be possible to add that in the /po directory ?
Other methods like Weblate / POEditor could be ok for translations too :)

**Comment by Sjoerd1993** [comment]
Hey, thanks a lot for offering to help out with translation!
This is actually something that is planned, and @cmkohnen mentioned that it's one of the things we should do after the 1.5 release. Personally I'm fluent in Dutch and Swedish as well, and @cmkohnen knows German also. So those are the languages we'd add either way. But of course if you can contribute with a French translation as well that would be great! 

Either way, this will be coming. I've only looked into this quickly right now, but it seems we need to fix a proper .pot file with the template for all strings. Then the .po files will contain the translations themselves. I'll be sure this thread gets updated once we've got a pot file ready!

This would also require us to add a setting for the language in the preferences as well imo, before releasing the actual translations in an update. Which is not really that difficult to add by the way, just writing that down for future reference when we actually implement this.

**Comment by cmkohnen** [comment]
Yes, localization, was something I wanted to get working for the next version. Thanks for the interest in helping!
As I personally haven't worked with gettext before, this is something, I need to figure out myself properly first. Probably the main reason I didn't took the time to properly address this was, that the codebase was changing actively and I believe this messes up gettext.

Maybe to explain the current state of localization:
All markup-defined UI has the translatable tag, meaning in theory it should get picked up by gettext. However on my last attempts nothing seemed to work.
Some parts of the code have hardcoded English strings. Some of them are easily translatable, we just need to insert a call to gettext. Some other, especially ones in drop-down menus in edit windows require a bit more work to be correctly localized.

This would be next on my TODO-list, but I can't guaranty that I have the time to address it in the next few days.

**Comment by cmkohnen** [comment]
Well to give an update on the situation:
The reason It never seemed to work was GNOME Builder forcing the locale to be English. So after building a bundle just for fun, I noticed, that it was working perfectly well. Will open a pr soon that will update the localization setup and start working on the issues I mentioned too.
