### ISSUE TITLE
Allow importing single column data

### ISSUE THREAD

**Issue by WiseroOrb** [Sjoerd1993/Graphs#240]

**Comment by Sjoerd1993** [comment]
I can see that being useful in some cases, I'll take a look at it and add this functionality when I've got time either today or tomorrow.

**Comment by Sjoerd1993** [comment]
This should be possible in the next 1.5.2 release, which I'm planning release relatively soon as it contains an important fix. (Saving multiple files at once is broken in the latest release at the moment)
