### ISSUE TITLE
[suggestion] Add linear regression in Mathematical Operations

### ISSUE THREAD

**Issue by matbme** [Sjoerd1993/Graphs#246]
First of all, I'd like to thank you for this amazing application. You have already saved me countless hours by not having to figure out how to properly adjust Matplotlib and Seaborn in code :D

One feature I think would be nice to have is the ability to generate a linear (and maybe even quadratic) regression line for the data in a specific dataset, probably by using the least squares fit from either [Numpy](https://numpy.org/doc/stable/reference/generated/numpy.linalg.lstsq.html) or [Scipy](https://docs.scipy.org/doc/scipy/reference/generated/scipy.linalg.lstsq.html#scipy.linalg.lstsq).

**Comment by Sjoerd1993** [comment]
Hey,

Thanks for the kind words. This is actually a feature that is on my radar and was the next "proper" thing I was thinking of implementing.

I've done this code-wise with scipy in the past and that works quite well. Scipy is already a dependency of Graphs anyway, so it's a perfect fit for this feature.

Right now I'm in the middle of finishing my PhD thesis (printing starts on the 2nd of May), so at the moment my time is rather limited. But I will take a look at this next week.

The biggest open question is more about the UX-side of this. But I've got some ideas there. In principle it should be possible to get a nice window where you can specify a custom function. And then put the coefficients in the equation name when it's added to the data set. 

Either way, it is in my radar. I'll take a look at it next week after I've handed in my thesis :)

**Comment by cmkohnen** [comment]
Hey, if this is still on the radar, I might have come up with some design suggestions.

I'd propose a dialogue window with "live updates". Generally a dialogue could be invoked via the add menu or a new context menu for items.
Introducing a context menu for items could also add features such as move up/down or export just this item.

The dialogue should contain (at the least) information about the actual equation "being used" to generate a regression (e. g. `1.56x + 6.7` for linear regressions) as well as the type (mx + b, ax² + bx + c, etc.). The latter might be changed on the fly by the user.
Also including the sum of R² would definitely be useful here.
It should also be possible to specify the name of that newly generated item (empty by default and using the equation name if it stays empty).

The actual item should only be generated and added, when that dialogue is confirmed.

**Comment by Sjoerd1993** [comment]
This is definitely still on the radar, and I was hoping to implement this with the 1.7 release. 

I was actually planning to properly get started with this, this week or so. Live updates would be very useful, as it would give a nice and intuitive way to get good initial values for the fitting process.

My initial plan was indeed to do this with a dialog window, where I was thinking to invoke it from the Mathematical Operations category. Then which data set to plot for could then be chosen from a drop-down menu. Having said that, a context menu on the items themselves is quite intriguing and probably a good idea either way.

Probably need to experiment a bit for the exact UI for the equations to fit to here. If someone wants to fit something to y = a*x + b*x^2 + c, then we have three free parameters. Ideally it should be possible to specify an initial guess for these parameters, as well as boundaries for these fits. This can possibly be done from another dialog within this fitting dialog.

Just letting the user type their initial equation (e.g. y=1.4x + 6x^2 + 3) may work. But then it becomes impossible to art fixed parameters. And it would also be nice to be able to fit for the exponents. 

Some basic statistics (such as R2) should definitely be given. Also having some basic pre-set types are nice to have, as I expect basic linear regression being the most popular type by far. So at the very least I want to implement linear regression first. And perhaps then think about how to neatly add a support for custom types.
