### ISSUE TITLE
Another big refactoring

### ISSUE THREAD

**Issue by cmkohnen** [Sjoerd1993/Graphs#251]
I'm opening this issue to track progress on another major refactor I'm planning next. As to avoid huge single-pr changesets I'll split this into different ones.

- [x] Work with `GFile` and bundle static files inside the gresource
Wherever possible work with `GFile`. This enables us to move static data files inside the gresource. This saves on fs overhead and maybe speeds some things up a bit. This is a multi-step process within itself.
    - [x] https://github.com/Sjoerd1993/Graphs/pull/250
    - [x] Rewrite the style-parser to be more inline with the upstream one and to work with `GFile` as well. The upstream one (currently in use) is a bit clunky imo and duplicates quite a few checks. This allows to have the same underlying system for editing styles as for setting params to use in the plot.
    - [x] Bundle template styles inside gresource as well

- [x] Split off config load and save
Create functions inside `file_io.py`, that take in a `GFile` and return a json object and respectively write a json object to a file. Also fix check_config getting called twice for some reason.

- [x] Rework data import
  - [x] Move settings for each import mode to a different config file
  - [x] Restructure `ImportSettings` to accommodate for different import modes
  - [x] Move logic to determine which import mode to use as well as `ImportSettings` to a new file

- [x] Various minor improvements along the way

To really work on this, I'll probably have time starting somewhere in the later next week.

**Comment by Sjoerd1993** [comment]
Just to comment on some of these points.

>  Work with GFile and bundle static files inside the gresource

I've been looking at this superficially at some points as well, and indeed this would help in general in some areas so agreed here. It also allows us to access some more convenient functionalities which could clean up things a little bit, and improve things in edge cases. 

>  Split off config load and save

Could you elaborate on what exactly would be split? Config load and split are already separated in general. But overall, I'm always happy with further improvements and reducing coupling between different functions.

**Comment by cmkohnen** [comment]
> > Split off config load and save
> 
> Could you elaborate on what exactly would be split? Config load and split are already separated in general. But overall, I'm always happy with further improvements and reducing coupling between different functions.

The main thing was just moving the function to import any json object from a file or write one for that matter to file_io, as right now we have duplicated logic for opening a config file

**Comment by cmkohnen** [comment]
I was also thinking about how to handle Graph labels while importing. As of now we override the labels if guess_headers is true or the format is xrdml or xry.
My proposal would be to add parameters xlabel and ylabel to each item. If an item gets added, which has these set (default would be an empty string) the labels will get updated if they are the default value. If they aren't the item can be plotted to the other axis if possible. If both axes are occupied, the item will be plotted normally, but no labels will be visually changed (maybe we even add a toast).
