### ISSUE TITLE
Dialogs don't follow HIG

### ISSUE THREAD

**Issue by cmkohnen** [Sjoerd1993/Graphs#298]
most action dialogs (I'd categorize them as such) do not follow the HIG.
The relevant article [here](https://developer.gnome.org/hig/patterns/feedback/dialogs.html#action-dialogs) describes, how they should be layout.
Most notably the accept button in the top right corner and the discard/cancel button in the top left one.
The pattern found the most in graphs atm is the accept buton all the way at the bottom of each dialog and a regular close (x) button in the top right corner.

The solution would be to somehow hide the x of each window, move the button and add a simple cancel button to each.

**Comment by Sjoerd1993** [comment]
I've been looking around a bit, and indeed there's a bunch of dialogs that I would say fall in this category and do not follow this guideline. Just quickly, this would at least include:

- Add data (advanced)
- Transform dialog
- Add data from equation
- Add new style

I won't say these dialogs are in a bad shape, but I do think we should try and adhere to follow the HIG, and therefore adapt them to this description.. The confirmation dialogs (when deleting a style for instance) should be OK, although some/most of them can be replaced by a Toast with an undo button at some point.
