### ISSUE TITLE
Snap package requires Blueprint 0.8.1

### ISSUE THREAD

**Issue by Sjoerd1993** [Sjoerd1993/Graphs#301]
With the latest build we've moved to blueprint 0.8.1, which introduces some breaking changes in the syntax. The latest version in the Ubuntu repositories is still from 0.6.x, and therefore fails to build right now. I am unsure if they'll upgrade before Ubuntu 23.10. I don't see any PPA available either, so it seems the snap manifest needs to build blueprint from source.

I think that should be possible, but I don't really know how to do this using snapcraft. Maybe @soumyaDghosh has some ideas here? Basically, building blueprint-compiler needs to be build from the source like we do in the Flatpak [here](https://github.com/Sjoerd1993/Graphs/blob/main/blueprint-compiler.json). It's maybe good anyway to just set these (the Flatpak and the Snap) to build from the same commit anyway, as to make sure both versions are more or less identical.

**Comment by soumyaDghosh** [comment]
> With the latest build we've moved to blueprint 0.8.1, which introduces some breaking changes in the syntax. The latest version in the Ubuntu repositories is still from 0.6.x, and therefore fails to build right now. I am unsure if they'll upgrade before Ubuntu 23.10. I don't see any PPA available either, so it seems the snap manifest needs to build blueprint from source.
> 
> I think that should be possible, but I don't really know how to do this using snapcraft. Maybe @soumyaDghosh has some ideas here? Basically, building blueprint-compiler needs to be build from the source like we do in the Flatpak [here](https://github.com/Sjoerd1993/Graphs/blob/main/blueprint-compiler.json). It's maybe good anyway to just set these (the Flatpak and the Snap) to build from the same commit anyway, as to make sure both versions are more or less identical.


Don't worry, though I'm working on a `blueprint-compiler` snap, for now building it from source is not a big deal at all. I am sending a PR asap.

**Comment by Sjoerd1993** [comment]
Thanks for the quick reply, that's great! 

There's no huge hurry, but I was thinking of maybe releasing a point update later this week as there's some nasty bugs in the latest stable release that has since been fixed. Of course it would be good to release for Snap and Flatpak simultaneously, so at least there it would be good to fix that as well. Having said that, this first requires some testing to make sure such a release doesn't contain any obvious bugs. And I need to properly fix the issue that is solved in PR #288. So either way that would be later in the week. So it would be nice to have something working by Friday, but it's not a catastrophe if it needs to be postponed either.

Pushing the update somewhere this week would also allow us to get a small highlight in the [This Week in GNOME](https://thisweek.gnome.org/posts/2023/06/twig-99/) blog, announcing the Snap version as well as the localization support. Next version is nr 100, so it would be nice to squeeze us in there as well :)

**Comment by soumyaDghosh** [comment]
Done
