### ISSUE TITLE
Screenshots in the snap listing page

### ISSUE THREAD

**Issue by soumyaDghosh** [Sjoerd1993/Graphs#321]
Hi, I checked that @Sjoerd1993 have changed the screenshots in the snap listing page. But, the point is, those screenshots doesn't actually represent the snap. Though the snap supports multiple accent colours, but, a regular Ubuntu user will get it orange first. Also, the icons will also be yaru icons. So, should the screenshots be changed a little bit? I can try to reproduce the exact same screenshots.

Opinions on this is requested. Thanks.

**Comment by Sjoerd1993** [comment]
Thank you for the report, I changed the screenshots for consistency's sake, so that the Flathub release and Snap release got the same treatment if that makes sense. But you are correct, that the Snap screenshots should follow the Ubuntu theming by default, which is slightly different. 

Will recreate new screenshots to reflect that.

**Comment by Sjoerd1993** [comment]
I changed the screenshots to match the default Ubuntu settings, as that is what the vast majority of Snap users will get: https://snapcraft.io/graphs. (In fact, it seems all Snap users right now are using Ubuntu)

**Comment by soumyaDghosh** [comment]
For every snaps, the majority users are of the latest LTS release, means 22.04 here.

**Comment by Sjoerd1993** [comment]
Yes, I noticed. It shouldn't make a difference for the screenshots, but nevertheless it's interesting information. While Ubuntu LTS is the distro that I typically recommend to new people (despite preferring Fedora by a good margin myself), I was not aware it's actually the most commonly used release. Looking at bigger Snaps, the gap is quite significant actually.

Typically the conversation online is about the latest and shiniest releases. It's good to be aware that this discourse does not always reflect reality, most people just want something that works and don't really care that much about big upgrades every 6 months.
