### ISSUE TITLE
[Feedback wanted]: Rethinking default values

### ISSUE THREAD

**Issue by cmkohnen** [Sjoerd1993/Graphs#384]
As of right now, we offer a preference for pretty much every input field you are given when performing and action. This adds a lot of clutter and doesn't scale well, when adding more configurable file formats in the future (just to name an example).

To combat this issue, there are a few options, which each have their own benefits:

**1. Drop these preferences from UI**
This means they aren't accessible to the end user and if they want to change the behaviour, they'd have to modify these parameters every time they want to perform that action. If they really want to they could still dig into the config file and change these manually.

**2. Expose a "Save as default" Button on every action**
This helps both in making preferences more accessible and to the point as well as preserving functionality. A user could still customize how they want the action to behave.

**3. Simply save the last entered state**
Whenever an action is performed, remember the inputs. If this action is to be performed ever again, simply load the last inputs. This way, there isn't even the hassle of going to another menu or having another box to check when the wanted behaviour is having things to change. This will also have no effect on simply using defaults.

My personal preference tends towards the third option, but I'm hereby asking for feedback on that matter. Also feel free to suggest another way.

**Comment by Sjoerd1993** [comment]
I've been thinking about these things as well, and my personal thought also went with this third option.

As there's no real use for instance to have a separate setting for the default filetype to save pictures in for instance, it will probably be more convenient to just stick with the latest value and save these to the config json upon saving. Same holds for many other settings, which would allow us to streamline things quite a lot. 

I'll look a bit more into most points in the review a bit later as well as I have time, currently writing this from the car :)

**Comment by Sjoerd1993** [comment]
So just going through the settings themselves, I'll go for setting by setting:

**Default Export Options**: 
I think all of these can actually maybe be removed. When saving a figure, we get a small pop up where all these settings can be set anyway. Perhaps it's cleanest to just remember those settings each time by saving to config upon saving a figure. Then this entire category can be removed.

**Action behaviour**
If anything, this one should probably be moved to other either way as it's currently only one setting. My intention was to introduce some more settings as well, for example to finetune the smoothening behaviour for instance. For this particular setting, I can see the argument of removing it and have one behaviour that should be obvious and work. However, in this particular case I can see the argument for both. Personally I use it to center rocking curves, where an intensity peak is given in the middle coordinate. That middle coordinate should be exactly at 0. For my personal use case "Center to peak intensity" is the definite best behaviour. But I recognize that "Center at middle coordinate" may be more useful for others. 

Either way, I'd say argue for keeping this setting as-is, or moving it to Other and giving it a subtitle.

**Other**
Clipboard length will be removed as an option, the other two are fine as-is. The only thing I could comment here is that we may want a "Hide unselected items" in "Figure settings" perhaps, but I think it's okay there. 

**Figure**
I'll take this entire tab at once, as my comments on these are the same for each category. The way I see this, is that this just sets the default "Figure settings" for a fresh setting. Personally, I really like to have this settings available as I personally actually use it. For instance, almost all of my personal plots are on a Logarithmic scale, but I want to have linear as default for most people as that's probably what most people use. 

I also tend to have "Scattering Angle 2Theta (degree)" and "Intensity (arb. u.)" on the X- and Y-axis respectively.  As 90% of my data fit to that pattern, it's just nice to have those defaults. I can imagine the same workflow for others, that they generally use it to plot their own data, and those generally have the same titles and such.

The styling section definitely should be there with all options, I have very little doubts about that category.

**Import settings**
I can argue a bit about these. On the one hand, we give a prompt when loading data now anyway. It made al lot of sense to have this "default behaviour" settings here before, when we had a "quick" option to add data. But now we have the prompt here anyway, it may not be as necessary, and we can just save whatever settings people used before.

On the other hand, I do see the point of having these here anyway, as you may want to import a specific annoying file that uses commas for whatever reason as decimal seperator, and each time you do that you'll have to remember to set it back again to a dot. So I'm in favour of keeping these as-is

**Add equation**
This one is a bit more difficult. But I think in this case, we can get away by removing this option and remembering the previous option that was used. That may be nicer in the workflow as well, as you often want to add similar equations anyway with similar limits and step sizes. So if you add two equations, you don't have to start from scratch each time, so I'm in favour of removing this one.

**Comment by Sjoerd1993** [comment]
Or to summarize my thoughts:

**Remove the following sections entirely from preferences, and remember last setting (option 3 in initial comment):** "Default Export Options" and "Add Equation"

**Keep as-is**:  "Labels", "Axes Settings", "Styling" and "Import Settings"

**Changes:**Other: Remove "Clipboard Length". Action behaviour: merge with "Other". 

And as always, these are just my thoughts right now. I'm open to an open discussion :)

**Comment by cmkohnen** [comment]
I mostly agree with your thoughts, but I'd treat import settings the same way as export options and the equation settings. If the example you mentioned really is a problem I'd use a "remember these settings" toggle (enabled by default) in the import window.

**Comment by Sjoerd1993** [comment]
> If the example you mentioned really is a problem I'd use a "remember these settings" toggle (enabled by default) in the import window.

I think that could be a neat compromise for that case. Both streamlining the actual settings (you don't have to go all the way to preferences to set the defaults, but can do it when needed), and allowing the user to import some obscure data without having to set things back to default afterwards. Definitely agree that such a toggle should be enabled by default by the way.
