### ISSUE TITLE
Transactional clipboard

### ISSUE THREAD

**Issue by cmkohnen** [Sjoerd1993/Graphs#412]
With recent changes to the whole codebase, it became possible to approach the clipboard from a new angle.

Instead of using the quite memory-intensive way of adding all items each time just one property of one of them changes, another solution would be to implement a transactional clipboard.

A possible implementation could be like the following workflow:
We differentiate between 3 types of item-actions:
- Adding/Deleting an item
- Swapping two items
- An Item's properties changed

In the last case we'd store only the item's key, the affected property and previous as well as current values.
During swap we'd only need to save the two keys.
During Delete/Add, we'd however need to store the whole item.

As many changes feature multiple sequential changes, automatically adding to the clipboard isn't feasible. I'd propose a way, where we listen to each of these changes but batch them together each time `add()` is called.
This would also reduce resource usage, when performing undo/redo as not every single item has to be serialized to a dict and back, which doesn't scale well with many items.

If we use a system like this it should definetely be implemented before we publish a new release, as it won't be easily migratable then.

**Comment by Sjoerd1993** [comment]
I agree that something like this is absolutely the way to go, and that it should be done before next release. The memory consumption is the weak point of the current clipboard style (although it will remain within a few MB's for the vast majority of cases), and there's a lot of duplication being there.

Thinking about what you wrote, there's some ideas in my head how to make something like that work. But it requires some extra time, and my schedule is somewhat busy last weeks. Will try and see if I can take a look this weekend at least.
