### ISSUE TITLE
Keybord Shortcuts dialog does not show some shortcuts

### ISSUE THREAD

**Issue by sabriunal** [Sjoerd1993/Graphs#427]
Hi, Keyboard Shorcuts dialog (aka Help Overlay) seem broken.

![Ekran Görüntüsü - 2023-08-29 14-01-32](https://github.com/Sjoerd1993/Graphs/assets/6218679/a9821d06-d489-4fd1-bb2c-5015af0c65bd)

It try to read accellerators from [action names](https://github.com/Sjoerd1993/Graphs/blob/main/data/ui/help_overlay.blp#L20) but there is no defination for shorcuts in [main.py](https://github.com/Sjoerd1993/Graphs/blob/main/src/main.py#L22-L28)

There are several triggers in the [Window.blp](https://github.com/Sjoerd1993/Graphs/blob/main/data/ui/window.blp#L7-L79)

**Comment by cmkohnen** [comment]
Probably caused by https://github.com/Sjoerd1993/Graphs/pull/416

**Comment by sabriunal** [comment]
Definitely.
