### ISSUE TITLE
Add Ubuntu theme support

### ISSUE THREAD

**Issue by Sjoerd1993** [Sjoerd1993/Graphs#492]
Since Ubuntu annoyingly pushes their own theme ([*cough*](https://stopthemingmy.app/)), the colours in dark-mode do not match in the Snap package. Since we've actually got over 300 active installs on Snap nowadays, this is something we should fix in the following release.

Using a seperate Yaru theme and applying that on the Snap would work. It would still lead to clashes when people use a custom theme using e.g. Gradience. But I'd argue that if you are going to use unsupported GNOME features, you're kinda on your own. Anyone using a custom theme can just create a custom theme in Graphs. But the out of the box experience on Ubuntu should be fixed.

**Comment by cmkohnen** [comment]
We could sign the open letter anyways, like a few other projects do with just "The Graphs Developers"

**Comment by Sjoerd1993** [comment]
> We could sign the open letter anyways, like a few other projects do with just "The Graphs Developers"

I was planning to do that anyway, but in the first instance under my personal name as I didn't want to speak for you without explicit permission. But if you're fine with it, I will open a PR to add Graphs in the list there.

Looking at the web page, it's also possible to add a badge to the Readme. I think it would be nice anyway to add a badge with the Flathub installs (6.6k right now), and one with the license as many projects do. It seems most projects that sign the open letter have it on their Readme. [See example](https://github.com/bragefuglseth/fretboard) here.

Shall we add one as well? It partly makes it clear that custom theming is not officially supported, and kind of takes a stance against distro's forcing their custom theme upon third party projects. Which is imo an issue with regard to testability.

**Comment by cmkohnen** [comment]
I'm fine with both signing the letter and adding the badges (as well as mentioned others) to the readme

**Comment by Sjoerd1993** [comment]
This is now mostly fixed with the Yaru styling.

**Comment by Sjoerd1993** [comment]
Just tested the Snap here, and this now works. The Snap package looks much better now:

![image](https://github.com/Sjoerd1993/Graphs/assets/68477016/21b893b7-5ea8-4abd-92f5-fedc86dc5442)

![image](https://github.com/Sjoerd1993/Graphs/assets/68477016/2479f01a-764a-4b65-9ec0-df29318ae79e)

Also tagging @soumyaDghosh, as you may be interested to see that the Snap colour scheme now looks consistent. It uses Yaru theming in the Snap package now, if the Yaru theme is set. If another theme than Yaru is set, it uses Adwaita like the Flatpak. So this should not affect Snap installs that don't use Ubuntu's version of GNOME.

**Comment by soumyaDghosh** [comment]
Just one word.

# Awesome
