### ISSUE TITLE
Style editor bugs

### ISSUE THREAD

**Issue by Sjoerd1993** [Sjoerd1993/Graphs#536]
These will be quite easy to detect, and I'm not really that nervous about things breaking during development when we're so heavily changing this part of the code. But since I don't really have too much time right now to look into it, I thought I'd at least just report these issues with regard to the style editor:

- Renaming an existing style does not work, it simply doesn't do anything. Some quick test actually shows this is also an issue in version 1.6.1. This is potentially a thing we could fix in a hotfix update as version 1.6.2. Wouldn't announce it in TWIG or anything, but the fix is probably easy to backport so it doesn't hurt making the stable version a bit better.
- In the current main branch, removing a style doesn't immediately update the style list. If I remove a style, nothing _seems_ to happen. But it is succesfully deleted (it's no longer editable or removable). Then deleting second style, will make the first style dissapear from the list. So it seems the update is triggered just after pressing remove, but before the actual deleting process.
- Similar issue persists when adding a style. It doesn't automatically add it. But adding/removing yet another style does trigger a refresh (but again, same bug so the extra style that was added/removed is not shown).
- Changing any attribute of a style is not automatically saved. If I change an attribute, and then back out to the overview of styles, and then go back into the style, the style shows the old value. But if I change an attribute, and then close the window, and then reopen it, then the change was correctly set. 
- After changing an attribute and closing the style editor, I get the following error:
```
Traceback (most recent call last):
  File "/app/lib/python3.11/site-packages/graphs/styles.py", line 115, in _on_file_change
    self._user_styles.pop(stylename)
KeyError: '.goutputstream-I0YVB2'
```

I think those are all the errors I saw with the style editor. Again, not too worried about them given just this part of the code is under construction atm, but I thought it'd be good to write them down.

**Comment by cmkohnen** [comment]
These are all fixed with #534
