### ISSUE TITLE
Consider removing item override on style preference option.

### ISSUE THREAD

**Issue by cmkohnen** [Sjoerd1993/Graphs#563]
Currently we check based on a preference if all items should be set to the new styles default options.

However I propose a different solution:
On a per-item per-property basis, check if that property is the default for the previously selected style (easy with latest refactors). If it is, that property is updated, if not, it is left the way it is.

Another variation could be, if only one property is not the default, leave the whole item as is.

My preference would be on the first suggestion. Feedback highly apprechiated.

**Comment by Sjoerd1993** [comment]
I think this is a reasonable thing to do, to further streamline the settings. 

To me, the two most sensible options are to either override everything, or go for the first mentioned option of overriding the defaults on a per-property basis (the first option). I feel like overriding on a per-item per-property basis would probably be the option that would lead to the most sensible workflow. That would allow to apply a style sheet on the open project, without losing any of the things you've changed. So I think that would lead to the least friction in most workflows.
