### ISSUE TITLE
Whether or not to frame the Graph

### ISSUE THREAD

**Issue by cmkohnen** [Sjoerd1993/Graphs#570]
As discussed in #566 already a bit, there should be a way to have the Graph not boxed.
We can bind this to styles or to figure settings.

I'm not sure which would make more sense. Technically both is possible and would need custom logic as just using rcParams "axes.spines.*direction*" wouldn't work. see the following:
![Bildschirmfoto vom 2023-11-14 11-52-45](https://github.com/Sjoerd1993/Graphs/assets/59118042/fc832ca8-8fb8-4772-aa48-4c48ab2092ce)

Another thing would be to argue how fine grained the user should specify these values.
I'm on the more simple side here:
A simple switch to specify whether or not the Graph should be boxed would suffice. In logic we then hide all spines, which aren't used.

Ideas welcome

**Comment by bertob** [comment]
This definitely looks like a better default, but also, the backgrounds on the graph and the right side of the window should be the same. Probably making the latter full-on white is better than having the graph on a gray background?

**Comment by Sjoerd1993** [comment]
With regard to the screenshot, I guess the data is plotted on the right-hand and bottom axis, right? I take the custom logic is in turning the correct splines in or off.

This could be done with the splines line width as well, just setting them to zero. But if we'd go with a box/no box approach, then this would require custom logic regardless.

Either way, I've been thinking about the same and I also landed on the conclusion of allowing a user to use a full frame, or only draw the line for the used axes. As I struggle to find a single use case for turning off active axes, or for drawing only one of the unused axes. So I too think that single option would be the way to go.

I was also thinking about exactly the same choice about binding this to figure settings or to the style. My gut feeling says binding to the style would make most sense, as it is part of the general styling imo.

**Comment by bertob** [comment]
What are the use cases for having a frame to begin with? Is this needed at all?

**Comment by Sjoerd1993** [comment]
>  Probably making the latter full-on white is better than having the graph on a gray background?

This is of course a matter of whatever we decide to be the "System Style". The gray background was to match with the Adwaita theming. Whilst a white background on a graph just makes sense, it maximizes contrasts and it is typically the default as well. If someone saves/exports a graph, they probably want to share it in a different format and there white typically works best. So either way, I think a white background sounds most sensible to me. Although, one can of course just turn on a different style if they want to export a graph, or alternatively export with transparent background.

If we'd match the content-view with the graph, that would be possible I guess. But it would leave us with a color-clash with the title-bar. We could theme the title-bar, but that feels very hacky and it would make the application feel somewhat alien with the rest of GNOME I fear. I think in general a gray background here would show more visual consistency with the rest of the GNOME DE, but I'm happy for any input on this. See screenshot below for an example with the background set to white, but with the "regular" title bar background.

![image](https://github.com/Sjoerd1993/Graphs/assets/68477016/3bd5106a-1c55-4313-b882-4581a1847a34)


> What are the use cases for having a frame to begin with? Is this needed at all?

Having a frame around the entire graph is very common in scientific publications. It boxes the graph itself quite clearly from the rest of the text, and it's the standard in tools such as matplotlib and Matlab. For me personally, it also adds a bit more perspective when looking at a graph, as it makes it easier to see at a glance where a data point lies with relation to the maximum value on the axis. Having the option to support an entire frame is something that I'd personally find at least an important one. Even if we'd only plot the active axes by default. And of course, if you want ticks on all sides you of course need an axis to draw ticks on. I'd say at least in academic settings (talking STEM research), it's more common with a frame than without one.

Just to re-iterate, I'm fine with dropping the entire frame by default though. The default view should be accessible and clear. But at least to me it is important to have the option to have a frame around the plot.

For reference here's one of the graphs that I have used in my PhD thesis. These were completely made in Graphs (even the data was generated in Graphs, as I derive the equation for these curves in the text and then use these plots to show a particular parameter affects the data):

![image](https://github.com/Sjoerd1993/Graphs/assets/68477016/1e20de37-5392-4e82-8636-16c0c15cf016)

**Comment by Sjoerd1993** [comment]
For reference again, here's an example of the styling with both the graph background and the "general background" are set to Adwaita-gray:

![image](https://github.com/Sjoerd1993/Graphs/assets/68477016/00fc79d7-916e-46ba-9146-68f5f50e4bce)

To me, it may actually look better than using complete white. But having a lack of frame kinda looks weird imo when the data does not fit within in the current span. But maybe it's not that bad as I imagine, see screenshot:

![image](https://github.com/Sjoerd1993/Graphs/assets/68477016/5b9ed1cd-704b-493a-a75b-e7c71c3dee14)

**Comment by bertob** [comment]
I don't have a super strong opinion one way or another, but FYI there is precedent for recoloring the entire right side to white when the content demands it, e.g. Fractal does it too.

As for the frame, fair enough. if it's common practice in academia it makes sense to have a setting somewhere :+1:

**Comment by Sjoerd1993** [comment]
> is precedent for recoloring the entire right side to white when the content demands it, e.g. Fractal does it too.

For now we've settled on using the light-gray background. This still works quite nicely, and the contrast is absolutely fine in my opinion. But it's good to know at least that there's at least precedent for this, I see in the Fractal Flathub screenshots that this is indeed the case.

See screenshots below for the current state:

![image](https://github.com/Sjoerd1993/Graphs/assets/68477016/ee48377b-b9e6-4c7c-b17d-940e38805d86)

![image](https://github.com/Sjoerd1993/Graphs/assets/68477016/77894865-2619-4307-90a8-32eb2ccf7aa9)

Note that we'll probably also add arrows to the axes ends here by default, like so:

![![image](https://camo.githubusercontent.com/d66e9aedd1840c7f626827c5f93d0f9b503c848276097621fd306b199cd2fc02/68747470733a2f2f6d6174706c6f746c69622e6f72672f737461626c652f5f696d616765732f737068785f676c725f64656d6f5f617869736c696e655f7374796c655f3030312e706e67)

**Comment by Sjoerd1993** [comment]
Closed with PR #571

**Comment by bertob** [comment]
Nice, looks great!
