### ISSUE TITLE
Consider dropping handle-duplicates preference (or some options)?

### ISSUE THREAD

**Issue by cmkohnen** [Sjoerd1993/Graphs#584]
I feel like in the vast majority of use cases, you'd want this setting to be on auto-rename anyways.

Keeping all options (which aren't really tested as it seems, since I've just fixed an old bug which wasn't noticed before) is kind of a maintenance burden.

I'd love to hear of use cases, where having this set to something else would make sense.
Using ignore, can lead you to wonder where your newly imported or generated data went (If you aren't consious that this is the selected behaviour).
Likewise just adding could cause problems, when trying to bulk edit items, and not being able to tell which items (having the same name) is which now.
Also overriding can be suprising as well, when you start to wonder where your data just went or why something is missing all of a sudden.

In many cases, having this setting on auto-rename reminds the user, that e. g. this has already been imported and they can make a decision based on the individual use case at that moment. (delete the old or new one respectively).

**Comment by Sjoerd1993** [comment]
Yes, I am inclined to agree here. Auto-rename is also non-destructive, so in the rare cases someone wants to ignore/replace an import, you can always just do this after importing.
