### ISSUE TITLE
Suggestion: Further UI Tweaks

### ISSUE THREAD

**Issue by Sjoerd1993** [Sjoerd1993/Graphs#591]
I'll probably look into this a bit more during the weekend, but I was planning to look into the following tweaks in the sidebar:

- Remove Inverse Fast Fourier Transform, and make the Inverse/Regular FFT choice a drop-down option
- Remove the modify section entirely, leaving only "Adjust" and "Transform"
- Move the "Translate/Multiply" section into "Adjust". But only use a single entry widget, with "Translate X", "Translate Y" , "Multiply X", "Multiply Y" as dropdown options.

This would clean up the amount of buttons a bit. And would get rid of the fact that "Adjust" and "Modify" basically mean the same thing. However, I'm open to suggestions here. Also with regard if it won't be too much of a GIMP situation, where there's a lot of different actions hidden behind a dropdown action.

**Comment by cmkohnen** [comment]
I'd be in favour of keeping Translate and Multiply separate from each other.


Another thing on my mind was adding a [Plots](https://github.com/alexhuntley/Plots) inspired overlay adding zoom, optimize limits and the figure settings, to move that out of the primary menu and give context clues as to what this configures exactly now.
