### ISSUE TITLE
App summary length

### ISSUE THREAD

**Issue by bertob** [Sjoerd1993/Graphs#593]
The current summary "Plot and manipulate data in a breeze" is slightly longer than 35 characters, it'd be great to get it below that to pass automated tests. How about just "Plot and manipulate data"?

Generally we recommend not including qualifiers like "simply" or "easily" anyway because it's generic and doesn't add anything (who would want to make their app difficult to use?).

**Comment by cmkohnen** [comment]
The readme and github description as well the [TWIG entry](https://gitlab.gnome.org/Teams/Websites/thisweek.gnome.org/-/blob/main/hebbot/config.toml#L1016) should be updated as well then

**Comment by Sjoerd1993** [comment]
The MR on TWIG [is up](https://gitlab.gnome.org/Teams/Websites/thisweek.gnome.org/-/merge_requests/97).
