### ISSUE TITLE
Allow opening files and projects from the File-Manager

### ISSUE THREAD

**Issue by cmkohnen** [Sjoerd1993/Graphs#614]
Currently the application has to be open and importing files or opening a project has to be invoked manually. Graphs should be able to open these files from the the File-Manager.

The technical implementation can follow the [`do_open`](https://docs.gtk.org/gio/signal.Application.open.html) vfunc. 

How to register graphs as an application capable of opening these filetypes is something, I haven't figured out yet

**Comment by Sjoerd1993** [comment]
Working on this now, will put up a PR soon.

**Comment by Sjoerd1993** [comment]
See #615, which mostly works but it breaks Snap and I'm not sure how to get icons to work for custom types.
