### ISSUE TITLE
Add system theme preview

### ISSUE THREAD

**Issue by Sjoerd1993** [Sjoerd1993/Graphs#632]
The system theme preview is not implemented yet, this should be considered a clear blocker for the next release:

![image](https://github.com/Sjoerd1993/Graphs/assets/68477016/d3f17f0e-2497-4e8a-a92e-d2fab74e6def)

Just as a side-note, there's not really any underlying motive to putting this up as a separate issue. I was just gathering open release blockers in the issue trackers. Once this issue and #494 are closed, I think we can put up an announcement for the beta itself on This Week in GNOME perhaps.

**Comment by cmkohnen** [comment]
I've looked a bit in the technical implementation and it seems, we have to stich this at runtime. You really can't cut svg images. So the technical implementation must generate both light and dark themes analog to gtk handles it internally. Then we can slice the images and stitch them together, save as a temp file and attach it to the system preview

**Comment by Sjoerd1993** [comment]
Either way they'd have to be generated in full probably. To stitch them together, what I do in Inkscape in such situations is to overlay them on top of each other and mask half of the top image. I am not completely sure if GTK render masks properly, I know some tools have some issues with my SVG masks. But that should theoretically be possible to be done on build-time, perhaps even with a call to a python script that does this. But again, I think it's fine to do this on runtime for now. Especially in the first implementation.

I guess you're suggesting to not generate a single svg file for the system preview with a mask, but rather to stick the Gtk.Image objects for light and dark mode into a single preview. I am not 100% sure how to slice and stitch such image objects if possible, but it sounds like a better approach to me than overlaying and masking.

Of course, if all else fails, it would be possible to ship a hard-coded system theme preview by hand. The disadvantage is that we'd have to rework those each time we make updates to the default stylesheet. But it would basically just be two different images (Yaru and Adwaita) to ship which isn't that bad. In fact, now the header bar takes the colour of the plot outline, we could potentially drop the separate system styles for Ubuntu (keeping Yaru, but having Adwaita as the system preferred style). Although I'm fine with keeping that as-is.
