### ISSUE TITLE
String freeze

### ISSUE THREAD

**Issue by Sjoerd1993** [Sjoerd1993/Graphs#660]
I think after the current PR's are merged, we can start thinking of a string freeze. But before freezing those definitely it may be good to double check all strings. Then once we've decided they're all OK, we can set a string freeze. So far these are my comments:

 - The categories in the sidebar are somewhat awkward as "Adjust" and "Modify" are somewhat synonymous. But I don't have better suggestions that will fit within the size. So I am okay with leaving those.
![image](https://github.com/Sjoerd1993/Graphs/assets/68477016/c8b3d0b5-4106-4dfb-962f-ad3b6547efdb)

- I'm fine with keeping them in, but are we completely sure that column-x and column-y need a subtitle? And are we ok without a subtitle for the delimiter? Also here I'm fine with keeping them as-is, just wanted to throw these out:
![image](https://github.com/Sjoerd1993/Graphs/assets/68477016/ab481b41-d60b-4856-b2da-04af7f0dd6a2)

- I noticed I've been using both left and left-hand to describe the left-hand axis. Would be better to be consistent. Perhaps just "Left" on all of them. (Same for the other directions)

![image](https://github.com/Sjoerd1993/Graphs/assets/68477016/853459e9-e2ed-40d5-803f-412ca3928b22)

I'll put up a PR to remove the "hand"  in the limits. Otherwise, I think most strings should be OK. But again just wanted to put the other ones on here as well for open discussion.

**Comment by cmkohnen** [comment]
Regarding the Delimiter Text I'd suggest adding "Character Sequence used to split Values".

For the Axis. I agree that removing the "-Hand" suffix is a good idea. Also since Graphs is not just for two-dimensional arbitrary length values, we might consider removing the "X-" or "Y-" prefix as well (or add it where it's currently missing to keep it consistent).
