### ISSUE TITLE
Weblate: Translation as Glossary

### ISSUE THREAD

**Issue by sabriunal** [Sjoerd1993/Graphs#663]
Hello, all translations appear to have been added as Glossary terms in Weblate.

This seems quite the opposite/unorthodox of the translations that I had contributed.

Could you please check it?

![resim](https://github.com/Sjoerd1993/Graphs/assets/6218679/54a16851-2790-4bf2-9cad-ded15d12a91e)

**Comment by Sjoerd1993** [comment]
Thanks for the report, I guess I've configured something wrong. 

Currently I'm away for Christmas, but I'll get back home tomorrow. Will have a look as soon as I get the opportunity which will hopefully be tomorrow.

**Comment by sabriunal** [comment]
Merry Christmas! This bug is not more important than Christmas.

**Comment by Sjoerd1993** [comment]
Thanks again for the report, it seemed to have been just a simple checkbox that I turned on by mistake.
