### ISSUE TITLE
Optimize Limits not doing anything

### ISSUE THREAD

**Issue by tedzards509** [Sjoerd1993/Graphs#675]
In the recent beta published to Flathub, when after opening the following csv: 
```
;m in kg;\Delta m in kg;F_G in N;\Delta F_G in N;s‘ in m ;\Delta s* in m;s = (s‘*L)/L‘ in m;\Delta s in m ;Steigung a in ;\Delta a in ;E in Pa;\Delta E in Pa
;0,0492;0,0002;0,4827;0,0020;0;0,001;0,0000;0,0003;;;;
;0,1042;0,0002;1,0222;0,0020;0,007;0,001;0,0021;0,0004;;;;
;0,1492;0,0002;1,4637;0,0020;0,012;0,001;0,0035;0,0004;;;;
;0,1990;0,0002;1,9522;0,0020;0,018;0,001;0,0053;0,0004;;;;
;0,2484;0,0002;2,4368;0,0020;0,025;0,001;0,0073;0,0004;;;;
;0,2990;0,0002;2,9332;0,0020;0,030;0,001;0,0088;0,0004;;;;
;0,3486;0,0002;3,4198;0,0020;0,037;0,001;0,0108;0,0004;;;;
;0,3982;0,0002;3,9063;0,0020;0,043;0,001;0,0126;0,0004;;;;
;;;;;;;;;;;;
;;;;;;;;;;;;
;L in m;\Delta L in m;;;;;;;;;;
;0,8;0,002;;;;;;;;;;
```
(Skip 1 row, ; delimiters, , for decimal, X row 3, Y row 7)

Clicking optimized limits doesn't do anything and doesn't return anything to the console. Might be related to #674

**Comment by Sjoerd1993** [comment]
Thank you for the report, can confirm this on my machine. Agree that it's probably related to #674. 

It doesn't matter **too** much as it should work either way, but is this `.csv` format generated using any software? Like LibreOffice? Haven't seen the semicolons like that before each row before, but then again I typically don't work that much with csv files directly. Good to have this data so I can make it work for this case as well.

**Comment by tedzards509** [comment]
The csv is exported from the Pages app off an iPad. But it was made using a template in which the first column was empty.
