### ISSUE TITLE
Feature request: Use first row of csv as axis-labels

### ISSUE THREAD

**Issue by tedzards509** [Sjoerd1993/Graphs#677]
When importing a CSV, the first row is often a good placeholder for the axis-labels.

**Comment by Sjoerd1993** [comment]
This should typically "just work", and does so for my own data. But it indeed does not work properly with the csv you show in #675, so it's probably a bug. Will look into it.

**Comment by Sjoerd1993** [comment]
This was indeed also a bug, the issue here is that we moved the `Item` class to Vala, and use setters and getters to set the label now. The relevant code was still trying to set the attribute directly.
