### ISSUE TITLE
Add way to open location after export

### ISSUE THREAD

**Issue by sophie-h** [Sjoerd1993/Graphs#692]
After exporting a graph I usually want to do something with it.

Maybe, having a button in the toast to open the export location with the file selected would be nice?

**Comment by Sjoerd1993** [comment]
Yes, I think that's a nice idea, haven't thought about this!

**Comment by Sjoerd1993** [comment]
This works quite well, will extend it to the other export options, and put up a PR later today.

[Skärminspelning från 2024-01-03 05-54-07.webm](https://github.com/Sjoerd1993/Graphs/assets/68477016/9fa9d42c-77e7-4d1a-97e8-78aa11ecd521)
