### ISSUE TITLE
All "Modify" operations print error when entry is invalid

### ISSUE THREAD

**Issue by sophie-h** [Sjoerd1993/Graphs#695]
When using operations like "Translate X" without having a valid value in the input field there is an error printed.

Maybe it makes sense to tweak this a bit. Is it possible to check if the value is valid while still supporting things like "pi"? In this case, it would maybe make sense to deactivate the button if the value is invalid.

Otherwise, it would make sense to report an error in the UI.

**Comment by Sjoerd1993** [comment]
Yes that's a good point, that's definitely doable. Something similar has been implemented in the Curve Fitting dialog already where a notice and a red error CSS class is displayed if entry is invalid.

Same should be done for the Add Equation dialog

**Comment by Sjoerd1993** [comment]
Sorry for the re-opening and closing. We have a feedback in the UI as it should, but was thinking we may want to do the same thing as in the curve fitting dialog and give a red error CSS when the value is invalid. Will probably do that anyway.
