### ISSUE TITLE
Allow to apply transformations only on selected dataset

### ISSUE THREAD

**Issue by sophie-h** [Sjoerd1993/Graphs#697]
It could be useful to have the option to apply a transformation only on one dataset.

**Comment by Sjoerd1993** [comment]
That's what the checkboxes in the data in the sidebar are for, transformations are only applied on data that is selected.

**Comment by sophie-h** [comment]
Uh, nice. Totally missed that. I guess one day a Help could make sense for people like me xD

**Comment by Sjoerd1993** [comment]
Yes, proper documentation is definitely on the list. During the holiday season I started somewhat on the webpage graphs.sjoerd.se, but there's still _a lot_ of work to be done on the webpage.
