### ISSUE TITLE
Strive to fulfill App Criteria for GNOME Circle

### ISSUE THREAD

**Issue by cmkohnen** [Sjoerd1993/Graphs#76]
## The why

Whether or not, we choose to apply to be part of GNOME circle, we should still try to fulfill the App Criteria, as it is a good standard of how to manage the app. Fulfilling this would be in no way a blocker for any short-term upcoming release, but something to keep in mind long-term. I'm going to update this issue every so often, to track progress.

#### General Quality

  - [x] Basic features and functionality work as expected
       - with recent changes to select functionality we are getting there, but this would be something to evaluate for the 1.5 release
  - [ ] Easy to get started on first run
       - Some sort of guidance should be in place to help guide new users on how to add data (especially  in what format it should be). The UI and UX are generally quite intuitive now.
  - [x] User reviews are generally positive. No repeated complaints about critical issues.
  - [x] No known issues that can lead to data loss

#### Maintenance

  - [x] Evidence of recent development activity
  - [x] Confidence in the maintainers' ability to reliably maintain the project
  - [x] Being careful about inflicting harm like data loss on users
  - [x] Keeping up with maintenance to at least using a supported runtime on Flathub

#### Technology Basis

  - [x] Uses GTK 4 + Libadwaita
  - [x] Uses the GNOME runtime on Flathub

#### Design

  - [ ] Follows the [Human Interface Guidelines](https://developer.gnome.org/hig/)
       - Mostly, should be something to adhere to starting with release 1.5 
  - [x] Dark mode works
      - [x] Contrast is maintained everywhere (no dark font color on dark background etc.)
      - [x] #89

#### Content

  - [x] Does not contradict the intentions of the [GNOME Code of Conduct](https://wiki.gnome.org/Foundation/CodeOfConduct)
  - [x] Does not promote cryptocurrencies or related services

#### Legal

  - [x] Has an [OSI-approved license](https://opensource.org/licenses) (GPL)
  - [x] No contributor license agreement (CLA)
  - [x] The software must work without installing proprietary software
  - [x] Not already member of another non-profit fiscal sponsor organization

#### Metadata

  - [x] App name follows [guidelines](https://developer.gnome.org/hig/guidelines/app-naming.html)
  - [x] App icon follows [guidelines](https://developer.gnome.org/hig/guidelines/app-icons.html)
  - [x] Screenshot quality ([more info](https://gitlab.gnome.org/GNOME/Initiatives/-/wikis/Update-App-Screenshots))
  - [x] "Summary" quality ([more info](https://gitlab.gnome.org/GNOME/Initiatives/-/wikis/App-Metadata#summary))
  - [x] .doap-file in repository exists and is up-to-date ([more info](https://gitlab.gnome.org/World/apps-for-gnome/-/blob/main/METADATA.md#doap))

#### Accessibility

  - [x] Can navigate to all elements via keyboard and use them
  - [x] Uses standard keyboard shortcuts ([more info](https://developer.gnome.org/hig/reference/keyboard.html))
  - [x] #90
  - [x] Large text mode works
       - Text in the graph stays the same size, but is still readable (same size as large text)
  - [x] Sufficient contrast between content and background
  - [x] Works with Orca (activate via `Alt+Super+S`)
      - [x] Image buttons have a tooltip

#### Repository

  - [x] Passing CI builds of the app
  - [x] Public issue tracker and code repository

#### Recommended

  - [x] Builds Flatpak in Builder out of the box
  - [x] Build system is Meson
  - [x] Making contributors aware that the [GNOME Code of Conduct](https://wiki.gnome.org/Foundation/CodeOfConduct) applies to the project

#### Circle App Criteria

  - [x] Available on Flathub
      - [x] Available for x64\_64 and aarch64
  - [x] No GNOME branding
  - [x] App ID is valid

**Comment by SjoerdB93** [comment]
Actually, Graphs is already available both on x64_64 and aarch64, see the Flathub page: https://beta.flathub.org/apps/details/se.sjoerd.Graphs

But overall agreed yes. In the longer term I think we should probably even apply to be part of GNOME Circles, but at least not until Graphs reaches some more maturity. But even if we don't, I agree it's a good checklist to try and follow either way so that we are app to standard with the GNOME ecosystem.

**Comment by cmkohnen** [comment]
> Actually, Graphs is already available both on x64_64 and aarch64, see the Flathub page: https://beta.flathub.org/apps/details/se.sjoerd.Graphs

Thanks, I didn't notice that

**Comment by SjoerdB93** [comment]
It doesn't show on the regular Flathub page, nor does it show in GNOME Software, so you'd either have to dig into the Flatpak manifest or look at the Flathub beta page to see this. So it's natural to miss.

Resizing indeed does give a white canvas where the MatplotlibWidget lies. I'm not really sure how to fix this, as I believe it's something in upstream Matplotlib (haven't tried in X11). Perhaps it's possible to catch a signal for resizing (not sure if anything is emitted) and set the widget to not visible. Should take a look at that issue at one point at least.

**Comment by cmkohnen** [comment]
As of https://github.com/SjoerdB93/Graphs/pull/137 All Elements are accessible via keyboard. The only feature not being viable using keyboard is selecting, panning and zooming via mouse.

Regarding conformity as a whole, I think it might be doable conforming starting with Release 1.5 as we are marginally close to doing so anyway. Save for Orca compatibility, there isn't a lot of work to be done, but a few small touches, that should be in the nex release anyway.

**Comment by cmkohnen** [comment]
With both https://github.com/Sjoerd1993/Graphs/pull/339 and https://github.com/Sjoerd1993/Graphs/pull/341 now merged, I'd apply for GNOME Circle now. I feel like the UI is in a good state.
Applications can be done [here](https://gitlab.gnome.org/Teams/Circle) but I'd leave that privilege to you @Sjoerd1993.
Any issues coming up could then be transparently tracked via a respective milestone.

**Comment by Sjoerd1993** [comment]
I'll go through the process of applying tomorrow morning. Was considering if we'd want those last PR's on the stable release (which would be part of the next patch I guess). But that may not be vital for the application itself either way.

**Comment by cmkohnen** [comment]
tracked by https://github.com/Sjoerd1993/Graphs/issues/385
